modLoader="javafml"
loaderVersion="[4,)"
license="Not specified"

[[mods]]
modId="crystalnexus"
version="1.0.0"
displayName="CrystalNexus"
displayURL="https://www.curseforge.com/members/chilllliii/projects"
logoFile="logo.png"
credits="Dcchill"
authors="Dcchill"

# Start of user code block mod configuration
# End of user code block mod configuration

    [[mixins]]
    config = "crystalnexus.mixins.json"

# Start of user code block custom mixins
# End of user code block custom mixins

[[dependencies.crystalnexus]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.176,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.crystalnexus]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"


[[dependencies.crystalnexus]]
    modId="jei"
    type="optional"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration